// Coordenadas aproximadas (x, y en %) para las casillas del tablero
export const boardPositions = [
  { step: 0, name: 'SALIDA', x:94, y: 94 },
  { step: 1, name: 'CALLE MOTIVACIÓN', x: 83, y: 94 },
  { step: 2, name: 'BONUS', x: 75, y: 94 },
  { step: 3, name: 'CALLE VACANTE', x: 66.5, y: 94 },
  { step: 4, name: 'PAGO DE IMPUESTOS', x: 58, y: 94 },
  { step: 5, name: 'CHARLA DE PASILLO', x: 50, y: 94 },
  { step: 6, name: 'PLAZA WELCOME PACK', x: 42, y: 94 },
  { step: 7, name: 'PADRINO TE AVALA', x: 34, y: 94 },
  { step: 8, name: 'CALLE FORMACIÓN', x: 25, y: 94 },
  { step: 9, name: 'CALLE ENTREGA', x: 17.5, y: 94 },
  { step: 10, name: 'PAUSA POR BURNOUT', x: 7, y: 94 },
  
  { step: 11, name: 'CALLE PROYECTO ESTRATEGICO', x:7, y: 82.7 },
  { step: 12, name: 'PAGO DE IMPUESTOS', x: 7, y: 74.5 },
  { step: 13, name: 'CALLE REUNIONITIS', x: 7, y: 66.2 },
  { step: 14, name: 'AVENIDA LADRONES DEL TIEMPO', x: 7, y: 58 },
  { step: 15, name: 'AFTERWORK TEMPRANO', x: 7, y: 50 },
  { step: 16, name: 'AVENIDA REUNIÓN CLAVE', x: 7, y: 41.5 },
  { step: 17, name: 'INCENTIVO', x: 7, y: 33.7 },
  { step: 18, name: 'CALLE VISIBILIDAD SELECTIVA', x: 7, y: 25.5 },
  { step: 19, name: 'PLAZA PRESENTACIÓN AL COMITÉ', x: 7, y: 17.2 },
  { step: 20, name: 'EXCEDENCIA GRATUITA', x: 7, y: 7 },

  { step: 21, name: 'CALLE RECONOCIMIENTO', x:17.5, y: 7 },
  { step: 22, name: 'TE HA TOCADO EL GORDO', x: 25, y: 7 },
  { step: 23, name: 'CALLE FEEDBACK', x: 34, y: 7 },
  { step: 24, name: 'CALLE EVALUACIÓN', x: 42, y: 7 },
  { step: 25, name: 'MÁQUINA DE CAFÉ', x: 50, y: 7 },
  { step: 26, name: 'AVENIDA DECIR NO', x: 58, y: 7 },
  { step: 27, name: 'CALLE DELEGAR', x: 66.5, y: 7 },
  { step: 28, name: 'ERROR PUNTUAL', x: 75, y: 7 },
  { step: 29, name: 'CALLE FLEXIBILIDAD', x: 83, y: 7 },
  { step: 30, name: 'IR A RRHH', x: 94, y: 7 },
  
  { step: 31, name: 'CALLE CUIDADOS', x:94, y: 17.2 },
  { step: 32, name: 'CALLE CARGA MENTAL', x: 94, y: 25.5 },
  { step: 33, name: 'PAGA EXTRA', x: 94, y: 33.7 },
  { step: 34, name: 'CALLE CONCILIACIÓN', x: 94, y: 41.5 },
  { step: 35, name: 'FIESTA DE NAVIDAD', x: 94, y: 50 },
  { step: 36, name: 'JUBILACIÓN ANTICIPADA', x: 94, y: 58 },
  { step: 37, name: 'CALLE PROMOCIÓN', x: 94, y: 66.2 },
  { step: 38, name: 'PAGO DE IMPUESTOS', x: 94, y: 74.5 },
  { step: 39, name: 'CALLE LIBERTAD', x: 94, y: 82.7 },
];